Rem //{{USR{{
@Echo Off
Rem // User logon script 
Rem // Generated by 'Panda Administrator by Panda Software'
Rem // Do not edit this file header
Rem // Call to domain logon script
Call %0\..\PMGRD002.BAT 
Rem // Insert new lines under line }}USR}}
Rem //}}USR}}
net use T: \\simula\ngomes.prof$
net use u: \\simula\com2a$
