//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.0.
// 
namespace SiSTUddi.xml
{
	using System.Xml.Serialization;

	/*
	 * Esta Classe foi gerada com XSD a partir do schema uddi_v2.xsd
	 */
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class accessPoint 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public URLType URLType;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	public enum URLType 
	{

		/// <remarks/>
		mailto,

		/// <remarks/>
		http,

		/// <remarks/>
		https,

		/// <remarks/>
		ftp,

		/// <remarks/>
		fax,

		/// <remarks/>
		phone,

		/// <remarks/>
		other,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class address 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("addressLine")]
		public addressLine[] addressLine;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string useType;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string sortCode;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string tModelKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class addressLine 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string keyName;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string keyValue;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class assertionStatusItem 
	{

		/// <remarks/>
		public string fromKey;

		/// <remarks/>
		public string toKey;

		/// <remarks/>
		public keyedReference keyedReference;

		/// <remarks/>
		public keysOwned keysOwned;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string completionStatus;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class keyedReference 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string tModelKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string keyName;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string keyValue;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class keysOwned 
	{

		/// <remarks/>
		public string fromKey;

		/// <remarks/>
		public string toKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class bindingTemplate 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("accessPoint", typeof(accessPoint))]
		[System.Xml.Serialization.XmlElementAttribute("hostingRedirector", typeof(hostingRedirector))]
		public object Item;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public tModelInstanceInfo[] tModelInstanceDetails;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string serviceKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string bindingKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class description 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Namespace="http://www.w3.org/XML/1998/namespace")]
		public string lang;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class hostingRedirector 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string bindingKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelInstanceInfo 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		public instanceDetails instanceDetails;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string tModelKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class instanceDetails 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		public overviewDoc overviewDoc;

		/// <remarks/>
		public string instanceParms;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class overviewDoc 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		public string overviewURL;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("bindingTemplates", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class bindingTemplates 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bindingTemplate")]
		public bindingTemplate[] bindingTemplate;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessEntity 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public discoveryURL[] discoveryURLs;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public contact[] contacts;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public businessService[] businessServices;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] identifierBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string authorizedName;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class discoveryURL 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string useType;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class name 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Namespace="http://www.w3.org/XML/1998/namespace")]
		public string lang;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class contact 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		public string personName;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("phone")]
		public phone[] phone;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("email")]
		public email[] email;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("address")]
		public address[] address;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string useType;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class phone 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string useType;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class email 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string useType;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessService 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public bindingTemplate[] bindingTemplates;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string serviceKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string businessKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessEntityExt 
	{

		/// <remarks/>
		public businessEntity businessEntity;

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement[] Any;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessInfo 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public serviceInfo[] serviceInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string businessKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class serviceInfo 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string serviceKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string businessKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("businessInfos", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessInfos 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessInfo")]
		public businessInfo[] businessInfo;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class dispositionReport 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("result")]
		public result[] result;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class result 
	{

		/// <remarks/>
		public errInfo errInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public keyType keyType;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool keyTypeSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int errno;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class errInfo 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string errCode;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	public enum keyType 
	{

		/// <remarks/>
		businessKey,

		/// <remarks/>
		tModelKey,

		/// <remarks/>
		serviceKey,

		/// <remarks/>
		bindingKey,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	public enum truncated 
	{

		/// <remarks/>
		@true,

		/// <remarks/>
		@false,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("findQualifiers", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class findQualifiers 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("findQualifier")]
		public string[] findQualifier;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class publisherAssertion 
	{

		/// <remarks/>
		public string fromKey;

		/// <remarks/>
		public string toKey;

		/// <remarks/>
		public keyedReference keyedReference;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class relatedBusinessInfo 
	{

		/// <remarks/>
		public string businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("sharedRelationships")]
		public sharedRelationships[] sharedRelationships;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class sharedRelationships 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("keyedReference")]
		public keyedReference[] keyedReference;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public direction direction;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	public enum direction 
	{

		/// <remarks/>
		fromKey,

		/// <remarks/>
		toKey,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("relatedBusinessInfos", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class relatedBusinessInfos 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("relatedBusinessInfo")]
		public relatedBusinessInfo[] relatedBusinessInfo;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModel 
	{

		/// <remarks/>
		public name name;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("description")]
		public description[] description;

		/// <remarks/>
		public overviewDoc overviewDoc;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] identifierBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string tModelKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string authorizedName;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("tModelBag", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelBag 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModelKey")]
		public string[] tModelKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelInfo 
	{

		/// <remarks/>
		public name name;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string tModelKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute("tModelInfos", Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelInfos 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModelInfo")]
		public tModelInfo[] tModelInfo;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class add_publisherAssertions 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("publisherAssertion")]
		public publisherAssertion[] publisherAssertion;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class delete_binding 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bindingKey")]
		public string[] bindingKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class delete_business 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessKey")]
		public string[] businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class delete_publisherAssertions 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("publisherAssertion")]
		public publisherAssertion[] publisherAssertion;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class delete_service 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("serviceKey")]
		public string[] serviceKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class delete_tModel 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModelKey")]
		public string[] tModelKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class discard_authToken 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class find_binding 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("findQualifier", IsNullable=false)]
		public string[] findQualifiers;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("tModelKey", IsNullable=false)]
		public string[] tModelBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int maxRows;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxRowsSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string serviceKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]

	public class find_business 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("findQualifier", IsNullable=false)]
		public string[] findQualifiers;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
	
		public string name;
		//public name[] name;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] identifierBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("tModelKey", IsNullable=false)]
		public string[] tModelBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public discoveryURL[] discoveryURLs;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int maxRows;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxRowsSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class find_relatedBusinesses 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("findQualifier", IsNullable=false)]
		public string[] findQualifiers;

		/// <remarks/>
		public string businessKey;

		/// <remarks/>
		public keyedReference keyedReference;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int maxRows;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxRowsSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class find_service 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("findQualifier", IsNullable=false)]
		public string[] findQualifiers;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		//public name[] name;
		public string name;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("tModelKey", IsNullable=false)]
		public string[] tModelBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int maxRows;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxRowsSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string businessKey;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class find_tModel 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("findQualifier", IsNullable=false)]
		public string[] findQualifiers;

		/// <remarks/>
		//public name name;
		public string name;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] identifierBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public keyedReference[] categoryBag;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int maxRows;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxRowsSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_assertionStatusReport 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		public string completionStatus;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_authToken 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string userID;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string cred;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_bindingDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bindingKey")]
		public string[] bindingKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_businessDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessKey")]
		public string[] businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_businessDetailExt 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessKey")]
		public string[] businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_publisherAssertions 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_registeredInfo 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_serviceDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("serviceKey")]
		public string[] serviceKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class get_tModelDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModelKey")]
		public string[] tModelKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class save_binding 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bindingTemplate")]
		public bindingTemplate[] bindingTemplate;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class save_business 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessEntity")]
		public businessEntity[] businessEntity;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("uploadRegister")]
		public string[] uploadRegister;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class save_service 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessService")]
		public businessService[] businessService;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class save_tModel 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModel")]
		public tModel[] tModel;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("uploadRegister")]
		public string[] uploadRegister;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class set_publisherAssertions 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("publisherAssertion")]
		public publisherAssertion[] publisherAssertion;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class validate_values 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessEntity", typeof(businessEntity))]
		[System.Xml.Serialization.XmlElementAttribute("businessService", typeof(businessService))]
		[System.Xml.Serialization.XmlElementAttribute("tModel", typeof(tModel))]
		public object[] Items;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class assertionStatusReport 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("assertionStatusItem")]
		public assertionStatusItem[] assertionStatusItem;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class authToken 
	{

		/// <remarks/>
		public string authInfo;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class bindingDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bindingTemplate")]
		public bindingTemplate[] bindingTemplate;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessEntity")]
		public businessEntity[] businessEntity;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessDetailExt 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessEntityExt")]
		public businessEntityExt[] businessEntityExt;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class businessList 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public businessInfo[] businessInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class publisherAssertions 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("publisherAssertion")]
		public publisherAssertion[] publisherAssertion;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string authorizedName;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class registeredInfo 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public businessInfo[] businessInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public tModelInfo[] tModelInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class relatedBusinessesList 
	{

		/// <remarks/>
		public string businessKey;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public relatedBusinessInfo[] relatedBusinessInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class serviceDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("businessService")]
		public businessService[] businessService;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class serviceList 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public serviceInfo[] serviceInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelDetail 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tModel")]
		public tModel[] tModel;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uddi-org:api_v2")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:uddi-org:api_v2", IsNullable=false)]
	public class tModelList 
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
		public tModelInfo[] tModelInfos;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string generic;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @operator;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public truncated truncated;

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool truncatedSpecified;
	}
}