<div align="center">
	<table width="100%">
		<tr bgcolor="#b0c4de" class="link">
			<td align="center">
				<a href="../index.html" class="link">Início</a>
				<a href="javascript:window.history.back()" class="link">Anterior</a>
				<a href="../Pesquisa/Pesquisar.aspx?tipoPesquisa=empresa" class="link">Procurar</a>
				<a href="../SiSTUDDI/publicar/index.aspx" class="link">Registrar</a>
				<a href="../docs/acerca.aspx" class="link">Acerca..</a>
			</td>
		</tr>
	</table>
</div>
